version: "3"
services:
  twerlo-image:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db



# named volumes..
volumes:
  mongo-db: